name: Daily Dev Log

on:
  schedule:
    - cron: "17 12 * * *" # todo dia 09:17 no horário de Brasília
  workflow_dispatch:

permissions:
  contents: write

jobs:
  update-dev-log:
    runs-on: ubuntu-latest

    steps:
      - name: Baixar repositório
        uses: actions/checkout@v4

      - name: Atualizar log diário
        run: |
          echo "## $(TZ=America/Sao_Paulo date '+%d/%m/%Y')" >> dev-log.md
          echo "- Registro diário de estudos, projetos e evolução como dev." >> dev-log.md
          echo "" >> dev-log.md

          git config user.name "Teuz"
          git config user.email "seutamamil@gmail.com"

          git add dev-log.md
          git commit -m "chore: atualiza dev-log diário" || echo "Nada para commitar"
          git push
